### ISSUE TITLE
Áudio no jogo

### ISSUE THREAD

**Issue by fspacheco** [GSimas/Game-C#3]
Acho que o problema com os arquivos de áudio é o tamanho. São 30 MB comprimidos, que devem ser armazenados sem compressão na memória. Então, não vai caber.
https://www.allegro.cc/forums/thread/615115

Testem o código seguinte. Se carregar .ogg (como funcionou no meu), mudem no projeto de vocês _al_load_sample_ para _al_load_audio_stream_

```
//gcc -Wall testeaudio.c -o testeaudio -lallegro -lallegro_audio -lallegro_acodec
//testar com ./testeaudio sounds/topgearsoundtrack.ogg
#include <allegro5/allegro.h>
#include <allegro5/allegro_audio.h>
#include <allegro5/allegro_acodec.h>
#include <stdio.h>

int main(int argc, char** argv)
{
  if (argc!=2) {
   printf("Uso: testeaudio nomearquivo\n");
   exit(1);
  }
  al_init();
  al_install_audio();
  al_init_acodec_addon();
  al_reserve_samples(1); // to create the default mixer/voice

  ALLEGRO_AUDIO_STREAM* stream = al_load_audio_stream(argv[1], 3, 1024);
  if (!stream) {
    printf("Erro ao carregar %s", argv[1]);
    exit(1);
  }
  al_attach_audio_stream_to_mixer(stream, al_get_default_mixer());

  while(al_get_audio_stream_playing(stream))
  {
    al_rest(0.1);
  }
  return 0;
}
```

**Comment by Clasr** [comment]
Com isso eu consegui fazer tocar um .wav, que no jogo em si não tava tocando também, mas o .ogg ainda não funciona.

**Comment by GSimas** [comment]
A gente optou por utilizar a extensão .ogg justamente por ser de menor tamanho (as músicas foram convertidas de .mp3 para .wav, .flac e .ogg, mas em formato wav e flac os áudios amplificaram de 6MB para 50MB, enquanto em .ogg resulta no máximo 5MB).
Em Windows qualquer extensão toca.
