### ISSUE TITLE
Comentários sobre o projeto

### ISSUE THREAD

**Issue by fspacheco** [GSimas/Game-C#4]
Documentação complementar ok.
Efeito visual excelente.
As estruturas Enemy_red e Enemy_blue são iguais. Poderiam usar uma só e colocar um campo para diferenciar o tipo de inimigo.
Por conta do comentário anterior, parte do código está repetida. É possível organizá-lo melhor. A repetição também aparece nas funções do background.
Está dando uma falha de segmentação no final. É alguma coisa que estão tentando liberar e que não tinha sido previamente alocada ou está sendo repetida a liberação. Não tive tempo para conferir, mas sugiro que vocês corrijam.
Vou submeter um pull request para corrigir o carregamento da imagem reprovado.png. Confiram.

**Comment by GSimas** [comment]
Quanto às estruturas Enemy primeiramente tínhamos a intenção de diferenciá-las, acrescentando alguma instância a mais na enemy_red, o que diferenciaria a movimentação, aparência e mecânica. Porém, no final, acabou-se involuntariamente permanecendo iguais.

Quanto à organização do código veremos o que será feito de acordo com as possibilidades.

Quanto aos backgrounds a "repetição" se dá por conta dos nomes diferentes dos arquivos de imagem. Com isso viu-se a necessidade de várias funções de inicialização de background (embora seja passível a avaliação da conversão dos nomes dos arquivos de imagem para um vetor de strings, aplicando assim um loop na função InitBackground)

Quanto à falha de segmentação creio que possa ser devido ao áudio (começou a aparecer após começarmos a inserir os arquivos de áudio, tanto em extensão .ogg, quanto em .wav ou .flac). Como se lembra, isto é algo que já estava sendo discutido em outra issue...

Quanto ao pull request veremos (e eventualmente aceitaremos, caso venha a contribuir com o projeto, após a análise do mesmo).

**Comment by GSimas** [comment]
Professor,

A falha de segmentação que fazia o jogo parar de responder foi consertada na Atualização 2.
A mesma acontecia quando o programa tentava desalocar elementos da memória que não foram carregados. Com isto foram aplicadas condições nos al_destroy's.

Estaremos vendo as outras questões...
